# Generated by Django 3.2 on 2023-09-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('college', models.CharField(choices=[('L', 'Lyceum'), ('P', 'Parnassus'), ('V', 'Virtus')], max_length=1)),
                ('grade', models.CharField(choices=[('9', 'G9'), ('10', 'G10'), ('11', 'G11'), ('12', 'G12')], max_length=2)),
                ('mentor', models.CharField(choices=[('A', '郭俊卿'), ('B', '赵胡梦鹤'), ('C', '刘芳雨'), ('D', '王倩宇'), ('E', '赵航'), ('F', '高行健'), ('G', '王思洋'), ('H', '朱宝杰'), ('I', '周芳颖'), ('J', '孙莹莹'), ('K', '赵昊一'), ('L', '李帅'), ('M', '兰文稚'), ('N', '王思洋'), ('O', '王一童'), ('P', '李肖阳'), ('Q', '于晓冬'), ('R', '苏盼文'), ('S', '王菁'), ('T', '李妍'), ('U', '邢文娟'), ('V', '王乃伟'), ('W', '徐颖雪'), ('X', '于江'), ('Y', '林帅')], max_length=1)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('last_change_data', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
